---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: install git
      apt:
        name: git
        state: latest

    - name: ensure the jenkins apt repository key is installed
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present

    - name: ensure the repository is configured
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
               https://pkg.jenkins.io/debian binary/'
        dest: /etc/apt/sources.list.d/jenkins.list
        state: present

    - name: Install java jdk
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install jenkins in ubuntu 20.04
      apt:
        name: jenkins
        state: present

    - name: start the jenkins server
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install firewalld
      apt:
        name: firewalld
        state: present

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: enable port 8080 for jenkins
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled

