---
- hosts: node2
  become: yes
  become_user: root
  tasks:
    - name: install git
      apt:
        name: git
        state: latest

    - name: Install java jdk
      apt:
        name: openjdk-11-jdk
        state: present

    - name: create a tomcat user
      user:
        name: tomcat

    - name: create a tomcat group
      group:
        name: tomcat

    - name: create a tomcat directory
      file:
        path: /home/node2/tomcat
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes

    - name: Download the tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
        dest: /home/node2/tomcat
        remote_src: yes

    - name: change ownership of tomcat directory
      file:
        path: /home/node2/tomcat/apache-tomcat-9.0.73
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes
        state: directory

    - name: copy tomcat service file from local to remote
      copy: 
        src: tomcat.service
        dest: /etc/systemd/system
        mode: 0755

    - name: copy the user's file to conf directory
      copy:
        src: tomcat-users.xml
        dest: /home/node2/tomcat/apache-tomcat-9.0.73/conf

    - name: copy the context file to META-INF directory
      copy:
        src: context.xml
        dest: /home/node2/tomcat/apache-tomcat-9.0.73/webapps/manager/META-INF/

    - name: copy the context file to host-manager META-INF directory
      copy:
        src: host-manager/context.xml
        dest: /home/node2/tomcat/apache-tomcat-9.0.73/webapps/host-manager/META-INF/

    - name: start and enable tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: true
        daemon_reload: true
